spring.application.name=FoodApplication
server.port = 8083


spring.datasource.url=jdbc:postgresql://localhost:5432/FoodApp
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.com.example.FoodApplication=DEBUG
logging.file.name=logs/app.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Email Configuration (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sggwhite321@gmail.com
spring.mail.password=aehdmeqqnqexeinq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# OTP settings (in seconds - 5 minutes)
app.otp.expiration-seconds=300
